export enum NotificationEnumType {
    SUB = "SUB",
    COMMENT = "COMMENT",
    LIKE_POST = "LIKE_POST",
    ANSWER_COMMENT = "ANSWER_COMMENT",
    LIKE_COMMENT = "LIKE_COMMENT",
    ADD_USER_DIALOG = "ADD_USER_DIALOG",
    REMOVE_USER_DIALOG = "REMOVE_USER_DIALOG",
    ADD_DIALOG = "ADD_DIALOG"
}
