// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.3
// source: attachments.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "attachments";

export enum AttachmentType {
  USER = 0,
  STORY = 1,
  POST = 2,
  COMMENT = 3,
  MESSAGE = 4,
  DIALOG = 5,
  LIKE = 6,
  FILE = 7,
  UNRECOGNIZED = -1,
}

export interface AddAttachmentDTO {
  parent_type: AttachmentType;
  parent_id: string;
  attached_type: AttachmentType;
  attached_id: string;
}

export interface GetAttachmentsDTO {
  parent_type: AttachmentType;
  parent_id: string;
}

export interface SetAttachmentsDTO {
  parent_type: AttachmentType;
  parent_id: string;
  attachments: Attachment[];
}

export interface Attachment {
  item_id: string;
  type: AttachmentType;
}

export interface Attachments {
  attachments: Attachment[];
}

export const ATTACHMENTS_PACKAGE_NAME = "attachments";

export interface AttachmentsServiceClient {
  addAttachment(request: AddAttachmentDTO): Observable<Attachment>;

  getAttachments(request: GetAttachmentsDTO): Observable<Attachments>;

  setAttachments(request: SetAttachmentsDTO): Observable<Attachments>;
}

export interface AttachmentsServiceController {
  addAttachment(request: AddAttachmentDTO): Observable<Attachment>;

  getAttachments(request: GetAttachmentsDTO): Observable<Attachments>;

  setAttachments(request: SetAttachmentsDTO): Observable<Attachments>;
}

export function AttachmentsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addAttachment", "getAttachments", "setAttachments"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AttachmentsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AttachmentsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ATTACHMENTS_SERVICE_NAME = "AttachmentsService";
