// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.3
// source: likes.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "likes";

export interface LikesCollection {
  id: string;
  unity: string;
  number_likes: number;
}

export interface CheckLikeDTO {
  user_id: string;
  collection_id: string;
}

export interface HasLiked {
  has_liked: boolean;
}

export interface LikesInfo {
  id: string;
  unity: string;
  number_likes: number;
  has_liked: boolean;
}

export interface CreateCollectionDTO {
  unity: string;
}

export interface GetCollectionDTO {
  id: string;
}

export interface AddLikeDTO {
  user_id: string;
  collection_id: string;
}

export const LIKES_PACKAGE_NAME = "likes";

export interface LikesServiceClient {
  addLike(request: AddLikeDTO): Observable<LikesInfo>;

  createCollection(request: CreateCollectionDTO): Observable<LikesCollection>;

  getCollection(request: GetCollectionDTO): Observable<LikesCollection>;

  checkLike(request: CheckLikeDTO): Observable<HasLiked>;
}

export interface LikesServiceController {
  addLike(request: AddLikeDTO): Observable<LikesInfo>;

  createCollection(request: CreateCollectionDTO): Observable<LikesCollection>;

  getCollection(request: GetCollectionDTO): Observable<LikesCollection>;

  checkLike(request: CheckLikeDTO): Observable<HasLiked>;
}

export function LikesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addLike", "createCollection", "getCollection", "checkLike"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("LikesService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("LikesService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const LIKES_SERVICE_NAME = "LikesService";
