// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.3
// source: messages.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "messages";

export enum AttachmentType {
  USER = 0,
  STORY = 1,
  POST = 2,
  COMMENT = 3,
  MESSAGE = 4,
  FILE = 7,
  UNRECOGNIZED = -1,
}

export interface GetMessagesDTO {
  dialog_id: string;
  take?: number | undefined;
  skip?: number | undefined;
}

export interface GetMessageDTO {
  id: string;
}

export interface CreateMessageDTO {
  attachments: Attachment[];
  dialog_id: string;
  msg: string;
  user_id: string;
}

export interface UpdateMessageDTO {
  attachments: Attachment[];
  dialog_id: string;
  id: string;
  msg?: string | undefined;
  user_id: string;
}

export interface DeleteMessageDTO {
  id: string;
  user_id: string;
}

export interface Attachment {
  id: string;
  type: AttachmentType;
  item_id: string;
}

export interface Message {
  id: string;
  attachments: Attachment[];
  dialog_id: string;
  user_id: string;
  msg: string;
  createdAt: string;
}

export interface Messages {
  messages: Message[];
}

export const MESSAGES_PACKAGE_NAME = "messages";

export interface MessagesServiceClient {
  createMessage(request: CreateMessageDTO): Observable<Message>;

  getDialogMessages(request: GetMessagesDTO): Observable<Messages>;

  getMessage(request: GetMessageDTO): Observable<Message>;

  updateMessage(request: UpdateMessageDTO): Observable<Message>;

  deleteMessage(request: DeleteMessageDTO): Observable<Message>;
}

export interface MessagesServiceController {
  createMessage(request: CreateMessageDTO): Observable<Message>;

  getDialogMessages(request: GetMessagesDTO): Observable<Messages>;

  getMessage(request: GetMessageDTO): Observable<Message>;

  updateMessage(request: UpdateMessageDTO): Observable<Message>;

  deleteMessage(request: DeleteMessageDTO): Observable<Message>;
}

export function MessagesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createMessage",
      "getDialogMessages",
      "getMessage",
      "updateMessage",
      "deleteMessage",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MessagesService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MessagesService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MESSAGES_SERVICE_NAME = "MessagesService";
