// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.3
// source: store.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "store";

export interface RemoveFileDTO {
  id: string;
}

export interface GetFileDTO {
  id: string;
}

export interface File {
  id: string;
  createdAt: string;
  user_id: string;
  filename: string;
  extname: string;
}

export interface RemoveFileRes {
}

export const STORE_PACKAGE_NAME = "store";

export interface StoreServiceClient {
  removeFile(request: RemoveFileDTO): Observable<RemoveFileRes>;

  getFile(request: GetFileDTO): Observable<File>;
}

export interface StoreServiceController {
  removeFile(request: RemoveFileDTO): Observable<RemoveFileRes>;

  getFile(request: GetFileDTO): Observable<File>;
}

export function StoreServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["removeFile", "getFile"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("StoreService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("StoreService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const STORE_SERVICE_NAME = "StoreService";
