syntax = "proto3";

package likes;

service LikesService {
    rpc AddLike (AddLikeDTO) returns (stream LikesCollection);
    rpc CreateCollection (CreateCollectionDTO) returns (stream LikesCollection);
    rpc GetCollection (GetCollectionDTO) returns (stream LikesCollection);
    rpc CheckLike (CheckLikeDTO) returns (stream LikesCollection);
}

message LikesCollection {
    string id = 1;
    string unity = 2;
    int32 number_likes = 3;
}

message CheckLikeDTO {
    string user_id = 1;
    string collection_id = 2;
}

message HasLiked {
    bool has_liked = 1;
}

message CreateCollectionDTO {
    string unity = 1;
}

message GetCollectionDTO {
    string id = 1;
}

message AddLikeDTO {
    string user_id = 1;
    string collection_id = 2;
}

