version: '0.0'
services:
  postgres: 
    container_name: postgres
    environment:
      PG_PASSWORD: root
      PG_DATABASE: stories
    image: postgres:latest
    restart: always
    volumes:
      - db:/var/lib/postgres
    ports:
      - 3306:3306
  stories: 
    container_name: stories
    build: .
    ports:
      - 5002:5002
    command: npm run start:prod
    depends_on:
      - postgres
volumes:
  db: