version: '0.0'
services:
  comments_db: 
    container_name: comments_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: comments
    image: postgres:latest
    restart: always
    volumes:
      - comments_db:/var/lib/postgres
    ports:
      - 5440:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres -d comments"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - comments_service
  comments: 
    container_name: comments
    build: .
    ports:
      - 5010:5010
    command: npm run start:prod
    depends_on:
      comments_db:
        condition: service_healthy
    extra_hosts:
      - "docker.for.win.localhost:host-gateway"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: comments
      POSTGRES_HOST: comments_db
      POSTGRES_PORT: 5432
    networks:
      - microservices
      - comments_service
volumes:
  comments_db:
networks:
  microservices:
    name: microservices
    external: true
  comments_service: