version: '0.0'
services:
  access_codes_db: 
    container_name: access_codes_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: access_codes
    image: postgres:latest
    restart: always
    volumes:
      - access_codes_db:/var/lib/postgres
    ports:
      - 5441:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres -d access_codes"]
      interval: 10s
      timeout: 5s
      retries: 5
  access_codes: 
    container_name: access_codes
    build: .
    ports:
      - 5011:5011
    command: npm run start:prod
    depends_on:
      access_codes_db:
        condition: service_healthy
    extra_hosts:
      - "docker.for.win.localhost:host-gateway"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: access_codes
      POSTGRES_HOST: access_codes_db
      POSTGRES_PORT: 5432
volumes:
  access_codes_db: